### ISSUE TITLE
Feature : Quests does not work on 0.12.12 - spt-aki 2.2.0

### ISSUE THREAD

**Issue by Woudidi** [sailro/EscapeFromTarkov-Trainer#133]
Target EscapeFromTarkov (0.12.12.16584) in P:\Battlestate Games\SPT.
>> Try #1 Compilation failed for master branch.
>> Try #2 Branch dev-0.12.12.16584 not found.
Trying to disable faulting feature(s): Quests.
>> Try #3 Compilation succeed for master branch.

**Comment by sailro** [comment]
Yes thank you.

It's already tracked here:
https://github.com/sailro/EscapeFromTarkov-Trainer/issues/122
