### ISSUE TITLE
0.16.2.35665

### ISSUE THREAD

**Issue by AquaOracle** [sailro/EscapeFromTarkov-Trainer#694]
Unable to compile trainer for version 0.16.2.35665. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues

**Comment by sailro** [comment]
Waiting for bleeding-edge builds from SPT.

**Comment by AnsXi** [comment]
> Wating for bleeding-edge builds from SPT。

Excuse me sir, may i ask when we can get the trainer for version 0.16.3.35392，I tried installing，but it doesn't work on client 0.16.3.35392

**Comment by 23DP4MOzol** [comment]
Target EscapeFromTarkov (0.16.2.35665) in E:\EFT.
>> Try #0 Compilation failed for master branch.
>> Try #1 Branch dev-0.16.2.35665 not found.
Unable to compile trainer for version 0.16.2.35665. Please file an issue here :
https://github.com/sailro/EscapeFromTarkov-Trainer/issues
